author: "Joseph Moniz <joseph.moniz@gmail.com>"
description: "A small piece of the haskell type class hierarchy ported to dart.\n"
homepage: "https://github.com/JosephMoniz/dart-concepts"
name: "concepts"
version: "0.2.0"
